### ISSUE TITLE
error: failed to run custom build command for `svm-rs-builds v0.1.15`

### ISSUE THREAD

**Issue by yurivict** [alloy-rs/svm-rs#104]
Build fails, but the error message below doesn't explain why:
```
     Running `/usr/ports/finance/foundry/work/target/release/build/svm-rs-builds-860c1b19b7173f60/build-script-build`
[svm-rs-builds 0.1.15] thread 'main' panicked at /usr/ports/finance/foundry/work/foundry-nightly-fca0a6c5ed3576a692c2444ec459e0ee5321e3e5/cargo-crates/svm-rs-builds-0.1.15/build.rs:113:57:
[svm-rs-builds 0.1.15] Failed to fetch releases: ReqwestError(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
[svm-rs-builds 0.1.15] stack backtrace:
[svm-rs-builds 0.1.15] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `svm-rs-builds v0.1.15`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/usr/ports/finance/foundry/work/target/release/build/svm-rs-builds-860c1b19b7173f60/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /usr/ports/finance/foundry/work/foundry-nightly-fca0a6c5ed3576a692c2444ec459e0ee5321e3e5/cargo-crates/svm-rs-builds-0.1.15/build.rs:113:57:
  Failed to fetch releases: ReqwestError(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
*** Error code 101
```

The log says that it tried to fetch something?
Fetching isn't allowed during package builds fir security reasons.

**Comment by DaniPopes** [comment]
Could either be a spurious error
